spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microrating
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka